name : CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : gradlew 실행 권한 부여
        run : chmod +x gradlew
        shell: bash

      - name : Build with Gradle
        run : ./gradlew clean build --info
        shell: bash