name : CI

on:
  push:
    branches: [ master ]

env:
  ZIP_NAME : springboot-webservice2
  S3_BUCKET_NAME: aws-webservice-springboot-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2

      - name : Set up JDK 8
        uses : actions/setup-java@v1
        with :
          java-version: 1.8

      - name : gradlew 실행 권한 부여
        run : chmod +x ./gradlew
        shell: bash

      - name : Build with Gradle
        run : ./gradlew clean build --info
        shell: bash

      # S3
      - name : Make zip file
        run : |
          mkdir -p before-deploy
          cp script/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r ./$ZIP_NAME.zip .
          cd ../ && mkdir -p deploy
          mv before-deploy/$ZIP_NAME.zip deploy/$ZIP_NAME.zip
        shell : bash

      - name : Configure AWS credentials
        uses : aws-actions/configure-aws-credentials@v1
        with :
          aws-access-key-id : ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.S3_BUCKET_SECRET_KEY }}
          aws-region : ap-northeast-2

      - name : Upload to S3
        run : aws s3 cp --region ap-northeast-2 ./deploy/$ZIP_NAME.zip s3://$S3_BUCKET_NAME/$ZIP_NAME.zip

      # codeDeploy
      - name : Code Deploy
        run : aws deploy create-deployment --application-name aws-springboot-webservice --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name aws-springboot-webservice-group --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$ZIP_NAME.zip